spring.application.name=bachelorProjectJava
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bachelor_project?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.data.mongodb.uri=mongodb+srv://dalton0x0:nijOUUZRbGSz6zlw@iticparis.qeamo.mongodb.net/?retryWrites=true&w=majority&appName=iticparis
spring.data.mongodb.database=demoDatabase
